### ISSUE TITLE
Branch deploy for re-re-revise branch?

### ISSUE THREAD

**Issue by apreshill** [batpigandme/tidyverse.org#15]
@batpigandme is this branch deploying somewhere on Netlify? Or shall I start a PR to trigger a deploy preview? Hoping that this is building- I am able to build locally (not done yet).

**Comment by batpigandme** [comment]
The re-revise is deploying, but I think you have to PR for deploy preview?
https://tverse-migration.netlify.com/blog/

**Comment by batpigandme** [comment]
Also just added a branch deploy for re-re-revise…but I'm not sure how to see it

**Comment by batpigandme** [comment]
Ah, figured it out: you need to have a custom domain to be able to do the branch-deploy thing where you prefix the url with the name of the branch.

**Comment by apreshill** [comment]
Throwing this here: https://re-re-revise.netlify.com/
