### ISSUE TITLE
Work on meta.html layout files to improve sharing images

### ISSUE THREAD

**Issue by apreshill** [batpigandme/tidyverse.org#19]
Maybe just redo this:
https://github.com/rstudio/education.rstudio.com/blob/master/layouts/partials/meta.html

**Comment by batpigandme** [comment]
Yes! Current setup for twitter cards doesn't work with bundled pages.

**Comment by apreshill** [comment]
Notes to self- need to rework the layout file. I cannot use the Hugo twitter template as we did in the education site because of the issue with locating feature images for past posts that we cannot rebuild. 

(if you test with our current site it will not work as the baseurl in the config.toml file would need to reflect the current netlify temporary url- twitter sharing images, for example, rely on absolute image paths versus relative)

https://github.com/batpigandme/tidyverse.org/blob/00209c3a4fec9d26c2b98b1ebbb2eb69bdf48761/config.toml#L6

**Comment by batpigandme** [comment]
Should we split this into getting twitter images to work going _forward_ and getting them to work retroactively?

**Comment by apreshill** [comment]
@batpigandme I believe https://github.com/tidyverse/tidyverse.org/pull/366 fixed both at the same time, as all past and future thumbnail images will have `*-sq* in the filename:

https://github.com/tidyverse/tidyverse.org/blob/f02ec436dd6a12614a6fe1fb37157eb4f9221171/themes/hugo-tourmaline/layouts/partials/meta.html#L31

This can be changed if you all want to use a different naming scheme.
