### ISSUE TITLE
Redirects

### ISSUE THREAD

**Issue by apreshill** [batpigandme/tidyverse.org#2]
Articles -> blog

**Comment by batpigandme** [comment]
Yes, I kinda sorta had that going, and then got scared about the fate of the image files. Conclusion: I need to test it out in a branch branch

**Comment by apreshill** [comment]
An alternative idea is to change this back to articles as a folder, but use this trick to change the base url in the `_index.md` file (I'll try to figure out cons to this approach):

https://github.com/rstudio/hugo-tourmaline/blob/master/exampleSite/content/articles/_index.md

**Comment by apreshill** [comment]
Can either of these posts be rebuilt without serious pain?

```
/articles/2018/08/contributing/ /articles/2017/08/contributing/
/articles/2018/08/purrr-0.2.3/ /articles/2017/08/purrr-0.2.3/
```

**Comment by batpigandme** [comment]
Contributing, definitely. purrrr-0.2.3…I wonder if we could literally rename and move manually
