### ISSUE TITLE
Make archetypes work

### ISSUE THREAD

**Issue by apreshill** [batpigandme/tidyverse.org#21]
Why???

They work from the terminal:

```
hugo new blog/help-me
```

This does not work:
```
hugo new blog/help-me/index.md
```

And new post add in also doesn't find the right archetype.

**Comment by batpigandme** [comment]
This is the issue being tracked in https://github.com/rstudio/blogdown/issues/414, right?

**Comment by apreshill** [comment]
page bundle archetypes are now indicated by a trailing slash:

https://github.com/rstudio/blogdown/issues/414#issuecomment-553251697

see https://github.com/rstudio/blogdown/issues/414
