### ISSUE TITLE
static/images

### ISSUE THREAD

**Issue by apreshill** [batpigandme/tidyverse.org#3]
What is this folder's fate? Do they need to be saved?

https://github.com/batpigandme/tidyverse.org/tree/re-revise/static/images

**Comment by batpigandme** [comment]
Ooh, I think we'd have to go in and change the rendered markdown md or html if we move them 😬

**Comment by batpigandme** [comment]
That said, we may need to do that with tags anyhow (again, we can't build them from source without rebuilding the whole article)

**Comment by apreshill** [comment]
Can you say more about tags?

**Comment by batpigandme** [comment]
So, we haven't used tags at all up until now (only categories). So, for example, there isn't an easy way to find all the dplyr posts. It's not so much that we want them to be visible everywhere as it might make them easier to find SEO-wise…

**Comment by batpigandme** [comment]
Another topic of discussion for today 😳

**Comment by apreshill** [comment]
OK the theme by default will have these taxonomies built-in (and thus enable automatic listing pages)- but it will require changing the YAML...which will in turn trigger a rebuild (I believe):

https://github.com/rstudio/hugo-tourmaline/blob/master/exampleSite/config.toml

**Comment by batpigandme** [comment]
Yeah…that's the killer. Hadley wanted to have subfolders for years, but the only way to do that and still have them all in one place is to add year to taxonomies, which means adding it to YAML, which means re-triggering a build…

**Comment by apreshill** [comment]
Well we can add a listing page way to group posts by year...a la:

https://alison.rbind.io/talk/page/3/

So there is a way to add date-based grouping based on what is already in the YAML. Tags that aren't already there yet are a different story though.

**Comment by batpigandme** [comment]
Ooh! OK, that's great to know. The only other option as far as package tagging goes that I can think of would be to pull them from the post titles ¯\\(°_o)/¯

**Comment by apreshill** [comment]
Not sure how to do that, but putting this here for reference:

https://gohugo.io/templates/lists/#group-content
