### ISSUE TITLE
Check post dates

### ISSUE THREAD

**Issue by apreshill** [batpigandme/tidyverse.org#7]
So this post:

https://www.tidyverse.org/articles/2018/08/tidymodels-0-0-1/

Is showing up in `blog/2017-07-29-tidymodels/index.Rmarkdown` with this YAML:

```
---
title: The tidymodels Package
author: Max Kuhn
date: '2018-08-06'
slug: tidymodels-0-0-1
description: > 
  tidymodels 0.0.1 is on CRAN.
categories:
  - package
---
```

The dates don't match up?

**Comment by batpigandme** [comment]
I was incredibly confused by that! Should we add a redirect?

**Comment by apreshill** [comment]
OK let's flag this post as odd and add `aliases` to the YAML (will it be hellfire if this post rebuilds? If so, we can do external redirect file, but for one-off redirects I like this approach):

https://gohugo.io/content-management/urls/#yaml-front-matter

**Comment by batpigandme** [comment]
It shouldn't be. It's the posts showing changes from version to version that are 💀 with re-rendering

**Comment by apreshill** [comment]
The image in this file needs a link and caption, unfortunately, as it renders like this on the new site:

https://re-re-revise.netlify.com/blog/2018/08/tidymodels-0-0-1/
